export interface Project {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  image: string;
  tags: string[];
  accent?: string;
  link?: string;
  github?: string;
  year?: number;
}

export const projects: Project[] = [
  {
    id: "mingming",
    title: "明明",
    subtitle: "Album Art / Visual Identity",
    description: "A quiet album cover built around negative space, restrained texture, and one deliberate focal point.",
    image: "/images/portfolio/mingming.png",
    tags: ["Album Art", "Visual Identity"],
    accent: "#383838",
    year: 2026,
  },
  {
    id: "25yongbutingxia",
    title: "25岁永不停下",
    subtitle: "Poster / Editorial",
    description: "An editorial poster treating motion as a typographic force, with dense rhythm contained by clean margins.",
    image: "/images/portfolio/25yongbutingxia.png",
    tags: ["Poster", "Editorial"],
    accent: "#555555",
    year: 2026,
  },
  {
    id: "taijie",
    title: "台阶",
    subtitle: "Artwork / Print",
    description: "A layered composition exploring hierarchy, repetition, and the visual tension between depth and flatness.",
    image: "/images/portfolio/taijie.png",
    tags: ["Artwork", "Print"],
    accent: "#666666",
    year: 2025,
  },
  {
    id: "xiaobuwuqu",
    title: "小步舞曲",
    subtitle: "Artwork / Series",
    description: "A small dance in still form: precise intervals, soft transitions, and a gentle sense of sequence.",
    image: "/images/portfolio/xiaobuwuqu.png",
    tags: ["Artwork", "Series"],
    accent: "#777777",
    year: 2025,
  },
  {
    id: "guoqi",
    title: "过期",
    subtitle: "Artwork / Narrative",
    description: "A visual note on expiration and memory, using grayscale tones to keep the story open and intimate.",
    image: "/images/portfolio/guoqi.png",
    tags: ["Artwork", "Narrative"],
    accent: "#383838",
    year: 2025,
  },
  {
    id: "yikehuichen",
    title: "一顆灰塵",
    subtitle: "Artwork / Minimal",
    description: "A minimal piece about scale and attention, with a single element carrying the composition.",
    image: "/images/portfolio/yikehuichen.png",
    tags: ["Artwork", "Minimal"],
    accent: "#555555",
    year: 2025,
  },
  {
    id: "moonlight",
    title: "月光 moonlight",
    subtitle: "Artwork / Tone Study",
    description: "A tone study in light and shadow, kept deliberately quiet so the material itself can breathe.",
    image: "/images/portfolio/moonlight.png",
    tags: ["Artwork", "Tone Study"],
    accent: "#666666",
    year: 2025,
  },
  {
    id: "piano",
    title: "piano",
    subtitle: "Artwork / Music Visual",
    description: "A visual response to piano music, rendered through rhythm, spacing, and restrained contrast.",
    image: "/images/portfolio/piano.png",
    tags: ["Artwork", "Music Visual"],
    accent: "#777777",
    year: 2025,
  },
  {
    id: "zixingren",
    title: "自行人",
    subtitle: "Artwork / Experimental",
    description: "An experimental composition where movement is implied rather than shown, leaving room for interpretation.",
    image: "/images/portfolio/zixingren.png",
    tags: ["Artwork", "Experimental"],
    accent: "#383838",
    year: 2025,
  },
  {
    id: "shaodance",
    title: "烧起来、舞蹈、浇灭",
    subtitle: "Album Art / Sequence",
    description: "Album artwork built around a three-part emotional arc, compressed into one strong visual frame.",
    image: "/images/portfolio/shaodance.png",
    tags: ["Album Art", "Sequence"],
    accent: "#555555",
    year: 2024,
  },
  {
    id: "yibaizhong",
    title: "一百種生活",
    subtitle: "Poster / Campaign",
    description: "A campaign poster celebrating many ways of living, with type and image held in careful balance.",
    image: "/images/portfolio/yibaizhong.png",
    tags: ["Poster", "Campaign"],
    accent: "#666666",
    year: 2024,
  },
  {
    id: "yorokobi",
    title: "悦びに咲く花",
    subtitle: "Artwork / Letterform",
    description: "A letterform-driven artwork where language becomes atmosphere and the flower is allowed to stay abstract.",
    image: "/images/portfolio/yorokobi.png",
    tags: ["Artwork", "Letterform"],
    accent: "#777777",
    year: 2024,
  },
  {
    id: "yeongwonhi",
    title: "지난 날은 영원히 혼수로 남아",
    subtitle: "Artwork / Bilingual",
    description: "A bilingual visual piece about the past staying dormant, balancing text with spatial silence.",
    image: "/images/portfolio/yeongwonhi.png",
    tags: ["Artwork", "Bilingual"],
    accent: "#383838",
    year: 2024,
  },
];

export const skills = {
  nodes: [
    { id: "direction", label: "Direction", group: "Design", level: 4, x: 110, y: 210 },
    { id: "type", label: "Typography", group: "Design", level: 5, x: 250, y: 92 },
    { id: "identity", label: "Identity", group: "Design", level: 4, x: 430, y: 80 },
    { id: "editorial", label: "Editorial", group: "Design", level: 4, x: 610, y: 190 },
    { id: "interaction", label: "Interaction", group: "Engineering", level: 4, x: 250, y: 330 },
    { id: "frontend", label: "Frontend", group: "Engineering", level: 4, x: 440, y: 360 },
    { id: "webgl", label: "WebGL", group: "Engineering", level: 3, x: 640, y: 315 },
    { id: "motion", label: "Motion", group: "Motion", level: 5, x: 430, y: 210 },
    { id: "systems", label: "Systems", group: "Engineering", level: 3, x: 250, y: 210 },
  ] as Array<{ id: string; label: string; group: "Design" | "Engineering" | "Motion"; level: number; x: number; y: number }>,
  edges: [
    { source: "direction", target: "type" },
    { source: "direction", target: "systems" },
    { source: "direction", target: "identity" },
    { source: "type", target: "editorial" },
    { source: "editorial", target: "identity" },
    { source: "systems", target: "interaction" },
    { source: "interaction", target: "motion" },
    { source: "interaction", target: "frontend" },
    { source: "frontend", target: "webgl" },
    { source: "motion", target: "webgl" },
    { source: "motion", target: "identity" },
  ] as Array<{ source: string; target: string }>,
  projectMap: {
    direction: ["mingming", "yibaizhong"],
    type: ["moonlight", "yorokobi"],
    identity: ["mingming", "shaodance"],
    editorial: ["25yongbutingxia", "yibaizhong"],
    interaction: ["portfolio-stack", "skill-constellation"],
    frontend: ["portfolio-stack", "skill-constellation"],
    webgl: ["hero-fluid", "portfolio-stack"],
    motion: ["hero-fluid", "taijie"],
    systems: ["portfolio-stack", "hero-fluid"],
  } as Record<string, string[]>,
};